version: "3.9"

services:
  pxy:
    build: ./proxy
    container_name: pxy
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    environment:
      APP_HOST: ${APP_HOST}
      API_PORT: ${API_PORT}
      WEB_PORT: ${WEB_PORT}
      API_CONTAINER: api
      WEB_CONTAINER: web
    depends_on:
      - web
      - api
    volumes:
      - certs:/etc/ssl:ro
    networks:
      - net

  api:
    container_name: api
    build: ./api
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    environment:
      API_PORT: ${API_PORT}
      APP_HOST: ${APP_HOST}
    volumes:
      - ./api/uploads:/app/uploads
    networks:
      - net

  web:
    container_name: web
    build: ./web
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    env_file:
      - .env
    environment:
      API_URL: ${API_URL}
    depends_on:
      - api
    networks:
      - net

#  web:
#    container_name: web
#    build: ./web-2
#    ports:
#      - "${WEB_PORT}:${WEB_PORT}"
#    env_file:
#      - .env
#    environment:
#      API_URL: ${API_URL}
#      VITE_API_URL: ${API_URL}
#    depends_on:
#      - api
#    networks:
#      - net

networks:
  net:

volumes:
  certs: