version: "3.9"

services:
  pxy:
    build: ./proxy
    container_name: pxy
    depends_on:
      - web
      - api
    env_file:
      - .env
    environment:
      APP_HOST: ${APP_HOST}
      API_PORT: ${API_PORT}
      WEB_PORT: ${WEB_PORT}
      API_CONTAINER: api
      WEB_CONTAINER: web
    volumes:
      - certs:/etc/ssl:ro
    networks:
      - net
    ports:
      - "80:80"
      - "443:443"

  api:
    container_name: api
    build: ./api
    env_file:
      - .env
    environment:
      API_PORT: ${API_PORT}
      APP_HOST: ${APP_HOST}
    volumes:
      - ./api/uploads:/app/uploads
    networks:
      - net
    ports:
      - "${API_PORT}:${API_PORT}"

  web:
    container_name: web
    build: ./web-vue
    depends_on:
      - api
    env_file:
      - .env
    environment:
      API_URL: ${API_URL}
    networks:
      - net
    ports:
      - "${WEB_PORT}:${WEB_PORT}"

#  web:
#    container_name: web
#    build: ./web-svelte
#    ports:
#      - "${WEB_PORT}:${WEB_PORT}"
#    env_file:
#      - .env
#    environment:
#      API_URL: ${API_URL}
#      VITE_API_URL: ${API_URL}
#    depends_on:
#      - api
#    networks:
#      - net

networks:
  net:

volumes:
  certs: