version: "3.9"

services:
  ssl:
    image: debian:latest
    container_name: ssl
    env_file:
      - .env
    environment:
      CERT_HOST: ${CERT_HOST}
      APP_HOST: ${APP_HOST}
    command: /bin/bash -c "apt-get update && apt-get install -y openssl && chmod +x /usr/local/bin/gen-certs.sh && /usr/local/bin/gen-certs.sh"
    volumes:
      - certs:/etc/ssl
      - ./ssl/gen-certs.sh:/usr/local/bin/gen-certs.sh
    networks:
      - net

volumes:
  certs:
